name: CI-CD 

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies and build project
      run: |
        npm install
        npm run build

    - name: Run tests and package project
      run: |
        npm run test
        npm run package

    - name: Upload package to release
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ./path/to/your/package.exe
        asset_name: your-package-name.exe
        asset_content_type: application/octet-stream
        api_key: ${{ secrets.GITHUB_TOKEN }}
